name: Docker Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build --file Dockerfile.full -t example-full .
      - run: docker build -f Dockerfile.pruned -t example-pruned .
      - run: docker image ls "example*"
